### ISSUE TITLE
do_disk

### ISSUE THREAD

**Issue by laurentperrinet** [bicv/SHL_scripts#12]
to avoid problems on the corners, use a disk to remove that pixels.

in https://github.com/bicv/SLIP/blob/master/SLIP/SLIP.py#L219

we have an example of how to do it:

```

        self.x, self.y = np.mgrid[-1:1:1j*self.pe.N_X, -1:1:1j*self.pe.N_Y]
        self.R = np.sqrt(self.x**2 + self.y**2)
        if not 'mask_exponent' in self.pe.keys(): self.pe.mask_exponent = mask_exponent
        self.mask = ((np.cos(np.pi*self.R)+1)/2 *(self.R < 1.))**(1./self.pe.mask_exponent)
        
```

**Comment by laurentperrinet** [comment]
it should be placed after each learning, before normalizing the dictionary by multiplying each filter with this mask.

**Comment by slike04** [comment]
I'm adding it right now, any advice on the exponential? I'm setting 1/8

**Comment by slike04** [comment]
LOL
<img width="354" alt="screen shot 2017-12-06 at 17 30 04" src="https://user-images.githubusercontent.com/29164075/33672618-eeebafa2-daaa-11e7-90d4-fb72cf7fc3ee.png">

**Comment by laurentperrinet** [comment]
Seems the disk is too small :-)

Or is it that you multiply it many times? Have you made a branch for that feature?

---
http://invibe.net

**Comment by laurentperrinet** [comment]
Best would be to make a branch for that feature and then merge it in the main code when it works.

**Comment by laurentperrinet** [comment]
as a quick test, if you binarize your mask (like ``mask = mask > .5``) you will quickly know ...

**Comment by laurentperrinet** [comment]
to answer, I would need you to push your code ! :-)

**Comment by slike04** [comment]
Sorry about that, just realized my laptop didn't recognize SHL as a git hub repository and didn't push the changes, I'll have that fixed asap

**Comment by slike04** [comment]
Wait,  can you the the changes I pushed in the past few days?
Because I cannot see them from the GitHub on my personal laptop, but I committed the changes from my Mac at the lab...Can you check?

**Comment by laurentperrinet** [comment]
Done using @slike04 's code in https://github.com/bicv/SHL_scripts/commit/e565c7b4d3ff2285b89f7888d8c50dbdd08261fb
