### ISSUE TITLE
implement Sandin et al (2016) by a binary gain vector

### ISSUE THREAD

**Issue by laurentperrinet** [bicv/SHL_scripts#24]
Is it possible in our current implementation to implement the heuristic behind Equi-probable MP by using a binary vector ``gain = (P < p)`` where  

This basically blocks those which are "too rich" and lets the other learn. For a given input, the equilibrium probability should be ``p_eq = L0_sparseness / M`` such that we may use something like ``p = p_eq * 1.1 ``

**Comment by slike04** [comment]
It is possible, it was actually my very first implementation were I had:
< q[p > p_eq]=0 >
but I actually think our current implementation works better since with the old one the basis were continuously jumping from being activated to being not.

**Comment by laurentperrinet** [comment]
From the paper, it seems this will be enough to reproduce their results. The ``alpha_homeo`` parameter could be used as ``p_threshold=p_eq*(1+alpha_homeo)`` as it seems to me we should control for its effect. The great aspect is that this will allow to control for the efficiency of your solution with respect to that implementation.

In practice, we should change the binary switch ``do_hap`` to a string (``homeo_method`` ??) which will select the homeostasis method...

**Comment by slike04** [comment]
Yep I can work on that, it was indeed sufficient to have an equiprobable coding.

**Comment by laurentperrinet** [comment]
so it seems that we implemented that. I have tested it in a notebook, now we should show the difference of convergence speed between the different methods.
