### ISSUE TITLE
implement ADAM to boost convergence

### ISSUE THREAD

**Issue by laurentperrinet** [bicv/SHL_scripts#32]
The Adam method adapts the step size depending on the amplitude of the gradient:

https://arxiv.org/pdf/1412.6980.pdf

proves to be faster the traditional fixed-step on-line stochastic gradient descent

**Comment by AngeloFranciosini** [comment]
Yep it seems to be the fastest, I'm on it!

**Comment by laurentperrinet** [comment]
oh, me too!

**Comment by AngeloFranciosini** [comment]
lol, I thought you assigned it to me. Attempted an implementation but I'm not getting it converging for the moment. If you're working on it I can go back to the AE. As you prefer

**Comment by laurentperrinet** [comment]
I am now testing it in the various homeostasis cases - at some point, we could do a comparison of the convergence speed...

**Comment by laurentperrinet** [comment]
showing comparative convergence curves in https://github.com/bicv/SHL_scripts/commit/f1aef44d62e160b946a0270e64d45610a4fa5e5d
