### ISSUE TITLE
redundant get_data function

### ISSUE THREAD

**Issue by laurentperrinet** [bicv/SHL_scripts#5]
the `` get_data`` function is present in the main scripts and in the tools scripts. We should just keep one... I suggest the one in the tools script.

**Comment by VictorBoutin** [comment]
agreed ! Same for plotting function... and others redundant function

**Comment by laurentperrinet** [comment]
This is resolved in https://github.com/bicv/SHL_scripts/commit/b125412deb9a719977fae4f265c2e4b16e175ed4 , no?
