### ISSUE TITLE
overflow in index when using fast P_cum

### ISSUE THREAD

**Issue by slike04** [bicv/SHL_scripts#8]
be careful 
the  " +1 " in 

`ceil = P_cum.ravel()[indices + 1 - 2 * (p_c == 1) + stick]`

generates an error so that when `indices[-1]=511` you get the error

`IndexError: index 51200 is out of bounds for axis 1 with size 51200`

it also means that when `indices[0]=511` then `ceil[0]=0` instead of `ceil[0]=1`

**Comment by slike04** [comment]
so I'm using 
`ceil = P_cum.ravel()[indices - 2 * (p_c == 1) + stick]`
Hope it won't crash :/

**Comment by laurentperrinet** [comment]
It will ! I will push a version that fixes it (I was busy finding the right expression...)

Will be there in 10 minutes... just git pull in your clone of the SHL_scripts

**Comment by slike04** [comment]
Ok Ok! I'll wait to launch the coding

**Comment by laurentperrinet** [comment]
The one to use is that in http://blog.invibe.net/posts/2017-03-29-testing-comps-fastpcum.html#optimizing-the-quantile-function:-vectorization-with-linear-interpolation
I added that in https://github.com/bicv/SHL_scripts/commit/9fc6e1cabbb9690c9db35b0c307dd9e592fc471c but do not know if that would be enough

**Comment by slike04** [comment]
I pulled it! Thanks for the last minute help! Finger crossed

bon weekend ;)

**Comment by laurentperrinet** [comment]
I’m off now :-)

The scripts will sync on my local copy and I will be able to push the changes from today

**Comment by laurentperrinet** [comment]
ok, everything is merged now in https://github.com/bicv/SHL_scripts/commit/66ffd522972bd21f16de864fdc20b2c97feb85ed 

If you want to know the details about the indexing, you can look at http://blog.invibe.net/posts/2017-03-29-testing-comps-fastpcum.html or download http://blog.invibe.net/posts/2017-03-29-testing-comps-fastpcum.ipynb and run it locally.
