### ISSUE TITLE
1/f pink noise initialization

### ISSUE THREAD

**Issue by laurentperrinet** [bicv/SHL_scripts#9]
1/f stats comes from averaging many images 

one possibility is to average, something like
`
dictionary = np.array_split(X_train, n_dictionary).mean(axis=??)
`
around line  https://github.com/bicv/SHL_scripts/blob/master/shl_scripts/shl_learn.py#L300

validate with a notebook in ``probe`` 
 - try it with no learning
 - include it in code and run a basic learning

**Comment by laurentperrinet** [comment]
that's implemented, right?
could you make a notebook called ``test-dictionary-initialization.ipynb`` in the probe folder to show how it behaves with respect to white noise?

**Comment by AngeloFranciosini** [comment]
Yep, I'm on it.
Which parameters/homeo_method should we use to test for an eventual improvement?
🤔

**Comment by laurentperrinet** [comment]
> On 17 Jan 2018, at 11:17, Angelo Franciosini <notifications@github.com> wrote:
> 
> Yep, I'm on it.
> Which parameters/homeo_method should we use to test for an eventual improvement?
> 🤔
> 

as you just need to run 2 learnings, use HEH - we are not 100% sure of the learning rule for HAP

**Comment by laurentperrinet** [comment]
I fixed some part of the code, for instance in https://github.com/bicv/SHL_scripts/commit/1af2bccbacac17b774e1bf64c8cd5688645f018d and https://github.com/bicv/SHL_scripts/commit/248258c20eef8be534307098485daf2a1a6b903c

one idea would be to generate 1/f noise of the size of the input image then use the whitening os this noise and finally grab patches for the initialization of the dictionary

**Comment by laurentperrinet** [comment]
showing comparative convergence curves in https://github.com/bicv/SHL_scripts/commit/58762f90e3d01633f8d2d0203573cbc415f42c05
